# Generated by Django 4.2.10 on 2024-02-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("tags", models.CharField(max_length=255)),
                ("stock_status", models.CharField(max_length=50)),
                ("available_stock", models.PositiveIntegerField()),
            ],
        ),
    ]
